github:
  label: GitHub
keycloak:
  label: Keycloak
setup:
  label: Setup
aws:
  label: AWS
traefik:
  label: Traefik
https:
  label: HTTPS
react:
  label: React
auto-tracker:
  label: Auto Tracker
n8n:
  label: n8n
groq:
  label: Groq
github-actions:
  label: GitHub Actions
automation:
  label: Automation
