github:
  label: GitHub
keycloak:
  label: Keycloak
setup:
  label: Setup
aws:
  label: AWS
traefik:
  label: Traefik
https:
  label: HTTPS
react:
  label: React
auto-tracker:
  label: Auto Tracker
n8n:
  label: n8n
groq:
  label: Groq
github-actions:
  label: GitHub Actions
automation:
  label: Automation
doc-engine:
  label: Doc Engine
journal:
  label: Journal
incident:
  label: Incident
iam-platform:
  label: IAM Platform
ai-debug-agent:
  label: AI Debug Agent
platform-docs:
  label: Platform Docs
mfa:
  label: MFA
scim:
  label: SCIM
ldap:
  label: LDAP
